"""`query` verb — BM25/dense/symbol/graph retrieval.

The auto router sends identifier-style lookups to the fast lane:
  - symbol exact
  - symbol trigram
  - BM25

Natural-language queries use the full lane:
  - BM25
  - dense vector retrieval
  - symbol exact
  - graph expansion from the fused seed set

Slices that extend this command:
  Slice 5 — cross-encoder rerank
  Slice 6 — Personalized PageRank
  Slice 15 — confidence + refined_queries hints
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np

from cbv import db, embedder, graph, paths, quantize, query_router, reranker

RRF_K = 60  # standard RRF damping constant
GRAPH_EDGE_KINDS = ("calls", "imports", "inherits", "references")
_DENSE_OVERFETCH = 6  # KNN over-fetch factor so category filtering still fills the limit
PRIMARY_CATEGORIES = {"source", "config"}
CONTEXT_CATEGORIES = {"test", "docs"}
CONTEXT_RRF_WEIGHT = 0.3  # context-tier RRF contributions are demoted vs primary


def run(ns: argparse.Namespace) -> int:
    if not ns.question.strip():
        print("query question must not be empty", file=sys.stderr)
        return 2

    repo_dir = paths.find_repo(ns.repo)
    if repo_dir is None:
        print(
            f"No index found for repo {ns.repo!r}. "
            f"Run `run.sh list` to see available indexes, or `run.sh "
            f"vectorize <url|path>` to create one.",
            file=sys.stderr,
        )
        return 2

    db_path = repo_dir / "index.sqlite"
    conn = db.open_db(db_path)
    try:
        try:
            db.assert_schema_v1(conn)
        except db.LegacySchemaError as e:
            print(str(e), file=sys.stderr)
            return 2

        lane = query_router.route(ns.question, getattr(ns, "lane", "auto"))
        expansion = {}

        if lane == "fast":
            fused = _rrf(
                [
                    _symbol_exact(conn, ns.question, limit=50),
                    _trigram(conn, ns.question, limit=50),
                    _bm25(conn, ns.question, limit=50),
                ],
                k=RRF_K,
                source_names=["symbol", "trigram", "bm25"],
            )
        else:
            # Primary tier: guaranteed pool of implementation code.
            bm25_primary = _bm25(conn, ns.question, limit=50, categories=PRIMARY_CATEGORIES)
            emb = embedder.make_embedder()
            qv = emb.embed([ns.question])[0]
            q_int8 = quantize.quantize_int8(qv.reshape(1, -1))[0]
            dense_primary = _dense(conn, q_int8, limit=50, categories=PRIMARY_CATEGORIES)
            sym_hits = _symbol_exact(conn, ns.question, limit=50)

            # Context tier: tests + docs, smaller budget, demoted in fusion.
            # meta/ and vendor/ chunks are generated by no lane -> excluded.
            bm25_context = _bm25(conn, ns.question, limit=4, categories=CONTEXT_CATEGORIES)
            dense_context = _dense(conn, q_int8, limit=4, categories=CONTEXT_CATEGORIES)

            # Seeds for graph expansion + PPR come only from the primary tier.
            primary_seed = _rrf(
                [bm25_primary, dense_primary, sym_hits],
                k=RRF_K,
                source_names=["bm25", "dense", "symbol"],
            )
            seed_ids = [cid for cid, _, _ in primary_seed[:20]]
            expansion = _graph_expand(conn, seed_ids)
            expansion_ids = list(expansion)
            ppr_candidate_ids = list(dict.fromkeys([*seed_ids, *expansion_ids]))
            ppr_hits = graph.personalized_pagerank(
                conn,
                seed_ids,
                expansion_chunk_ids=expansion_ids,
                candidate_chunk_ids=ppr_candidate_ids,
                iterations=10,
            )
            fused = _rrf(
                [bm25_primary, dense_primary, sym_hits, expansion, ppr_hits,
                 bm25_context, dense_context],
                k=RRF_K,
                source_names=["bm25", "dense", "symbol", "graph", "ppr",
                              "bm25", "dense"],
                weights=[1.0, 1.0, 1.0, 1.0, 1.0,
                         CONTEXT_RRF_WEIGHT, CONTEXT_RRF_WEIGHT],
            )
        candidate_rows = []
        candidate_passages = []
        for chunk_id, score, sources in fused:
            row = conn.execute(
                "SELECT file_path, kind, name, start_line, end_line, content "
                "FROM chunks WHERE id = ?", (chunk_id,)
            ).fetchone()
            if row is None:
                continue
            file_rel, kind, name, sl, el, content = row
            file_abs = (repo_dir / "source" / file_rel).resolve()
            candidate_passages.append(content)
            candidate_rows.append({
                "rank": 0,
                "file_absolute": str(file_abs),
                "file_relative": file_rel,
                "start_line": sl,
                "end_line": el,
                "kind": kind,
                "name": name,
                "score": round(float(score), 4),
                "preview": (content[:200] + "...") if len(content) > 200 else content,
                "why_this_was_returned": "+".join(sorted(sources)),
            })

        if lane == "full" and candidate_rows:
            rr = reranker.make_reranker()
            scores = rr.score(ns.question, candidate_passages)
            if len(scores) != len(candidate_rows):
                print(
                    f"reranker returned {len(scores)} scores for "
                    f"{len(candidate_rows)} candidate rows",
                    file=sys.stderr,
                )
                return 2
            for row, score in zip(candidate_rows, scores):
                row["score"] = float(score)
            candidate_rows.sort(key=lambda row: float(row["score"]), reverse=True)
            reranker_model = rr.model_id
            refined_queries = _refined_queries(ns.question, candidate_rows[: ns.top_k])
        elif lane == "full":
            reranker_model = None
            refined_queries = _refined_queries(ns.question, candidate_rows)
        else:
            reranker_model = None
            refined_queries = []

        final_rows = candidate_rows[: ns.top_k]
        for rank, row in enumerate(final_rows, start=1):
            row["rank"] = rank
            row["score"] = round(float(row["score"]), 4)

        blob = {
            "repo": ns.repo,
            "query": ns.question,
            "repo_dir": str(repo_dir),
            "pipeline_used": lane,
            "results": final_rows,
            "refined_queries": refined_queries,
            "expansion_size": len(expansion) if lane == "full" else 0,
            "reranker_model": reranker_model,
        }
        print(json.dumps(blob), flush=True)
        return 0
    finally:
        conn.close()


def _bm25(conn, query: str, *, limit: int, categories: set[str] | None = None) -> Dict[int, float]:
    """Return {chunk_id: bm25 rank-score} for top BM25 hits, optionally
    restricted to the given file categories."""
    if categories:
        placeholders = ",".join("?" for _ in categories)
        rows = conn.execute(
            "SELECT chunks_fts.rowid, bm25(chunks_fts) FROM chunks_fts "
            "JOIN chunks ON chunks.id = chunks_fts.rowid "
            f"WHERE chunks_fts MATCH ? AND chunks.category IN ({placeholders}) "
            "ORDER BY bm25(chunks_fts) LIMIT ?",
            (_fts_escape(query), *sorted(categories), limit),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT rowid, bm25(chunks_fts) FROM chunks_fts "
            "WHERE chunks_fts MATCH ? ORDER BY bm25(chunks_fts) LIMIT ?",
            (_fts_escape(query), limit),
        ).fetchall()
    return {int(r[0]): float(r[1]) for r in rows}


def _fts_escape(query: str) -> str:
    """Wrap each whitespace-split token in double quotes so FTS5 treats them as
    literal terms (no syntax injection through user input)."""
    parts = [p for p in query.split() if p]
    if not parts:
        return '""'
    quoted = ['"' + p.replace('"', '""') + '"' for p in parts]
    return " OR ".join(quoted)


def _dense(conn, q_int8: np.ndarray, *, limit: int, categories: set[str] | None = None) -> Dict[int, float]:
    """Return {chunk_id: -distance} for top sqlite-vec KNN hits, optionally
    restricted to the given file categories.

    sqlite-vec 0.1.x KNN cannot filter on a joined column, so when a category
    filter is set we over-fetch k = limit * _DENSE_OVERFETCH nearest, then
    filter and truncate in Python. When a category filter is set the result
    may contain fewer than `limit` hits if the requested categories are rarer
    than roughly 1-in-`_DENSE_OVERFETCH` of the nearest-neighbour window.

    Inverts distance so 'higher is better' is consistent with BM25 ordering
    (where smaller bm25 = better). The RRF fuse normalizes via rank order
    so absolute scales don't matter.

    Uses `vec_int8(?)` with a JSON string for the query vector because
    sqlite-vec 0.1.x rejects raw INT8 bytes (interpreted as float32).
    """
    qparam = db.vec_int8_param(q_int8)  # JSON string, NOT raw bytes
    if categories:
        rows = conn.execute(
            "SELECT v.chunk_id, v.distance FROM vec_chunks v "
            "WHERE v.embedding MATCH vec_int8(?) AND v.k = ? "
            "ORDER BY v.distance",
            (qparam, limit * _DENSE_OVERFETCH),
        ).fetchall()
        allowed = {
            int(r[0])
            for r in conn.execute(
                "SELECT id FROM chunks WHERE category IN ("
                + ",".join("?" for _ in categories)
                + ")",
                tuple(sorted(categories)),
            )
        }
        out: Dict[int, float] = {}
        for chunk_id, distance in rows:
            cid = int(chunk_id)
            if cid in allowed:
                out[cid] = -float(distance)
            if len(out) >= limit:
                break
        return out
    rows = conn.execute(
        "SELECT chunk_id, distance FROM vec_chunks "
        "WHERE embedding MATCH vec_int8(?) AND k = ? ORDER BY distance",
        (qparam, limit),
    ).fetchall()
    return {int(r[0]): -float(r[1]) for r in rows}


def _symbol_exact(conn, query: str, *, limit: int) -> dict[int, float]:
    q = _query_symbol_token(query)
    if not q:
        return {}
    rows = conn.execute(
        "SELECT DISTINCT chunk_id FROM nodes "
        "WHERE chunk_id IS NOT NULL AND kind != 'block' "
        "AND (short_name = ? OR name = ?) LIMIT ?",
        (q, q, limit),
    ).fetchall()
    return {int(row[0]): float(limit - idx) for idx, row in enumerate(rows)}


def _trigram(conn, query: str, *, limit: int) -> dict[int, float]:
    from cbv import identifiers

    q = _query_symbol_token(query)
    if not q:
        return {}
    grams = sorted(identifiers.trigrams(q))
    if not grams:
        return {}
    placeholders = ",".join("?" for _ in grams)
    rows = conn.execute(
        f"SELECT chunk_id, SUM(occurrences) AS score FROM symbol_trigrams "
        f"WHERE trigram IN ({placeholders}) GROUP BY chunk_id "
        f"ORDER BY score DESC LIMIT ?",
        (*grams, limit),
    ).fetchall()
    return {int(row[0]): float(row[1]) for row in rows}


def _graph_expand(conn, seed_chunk_ids: list[int], *, per_node: int = 3) -> dict[int, float]:
    if not seed_chunk_ids:
        return {}
    placeholders = ",".join("?" for _ in seed_chunk_ids)
    kind_placeholders = ",".join("?" for _ in GRAPH_EDGE_KINDS)
    rows = conn.execute(
        f"SELECT neighbor.chunk_id, MAX(edge.weight) AS score "
        f"FROM nodes seed "
        f"JOIN edges edge ON edge.src = seed.id OR edge.dst = seed.id "
        f"JOIN nodes neighbor ON neighbor.id = CASE WHEN edge.src = seed.id THEN edge.dst ELSE edge.src END "
        f"WHERE seed.chunk_id IN ({placeholders}) AND neighbor.chunk_id IS NOT NULL "
        f"AND edge.kind IN ({kind_placeholders}) "
        f"GROUP BY neighbor.chunk_id "
        f"ORDER BY score DESC, neighbor.chunk_id ASC "
        f"LIMIT ?",
        (*seed_chunk_ids, *GRAPH_EDGE_KINDS, max(1, len(seed_chunk_ids) * per_node)),
    ).fetchall()
    return {int(row[0]): float(row[1]) for row in rows}


def _refined_queries(query: str, rows: list[dict]) -> list[str]:
    if not rows:
        return [query]
    top_score = float(rows[0].get("score", 0.0))
    if top_score >= 1.0:
        return []
    names = [r.get("name") for r in rows[:5] if r.get("name")]
    return [f"{query} {name}" for name in names[:3]]


def _query_symbol_token(query: str) -> str:
    parts = query.strip().split()
    if not parts:
        return ""
    return parts[-1].strip(".,:;()[]{}<>!?\"'`")


def _rrf(
    rankings: List[Dict[int, float]],
    *,
    k: int,
    source_names: list[str] | None = None,
    weights: list[float] | None = None,
) -> List[tuple]:
    """Reciprocal Rank Fusion with optional per-ranking weights.

    `weights[i]` multiplies every RRF contribution from `rankings[i]`; it
    defaults to 1.0 for every ranking (classic RRF). `sources` is a tag list
    per chunk for debug output.
    """
    if source_names is None:
        source_names = [f"source_{idx}" for idx in range(len(rankings))]
    if len(source_names) != len(rankings):
        raise ValueError("source_names length must match rankings length")
    if weights is None:
        weights = [1.0] * len(rankings)
    if len(weights) != len(rankings):
        raise ValueError("weights length must match rankings length")

    aggregate: Dict[int, float] = {}
    sources: Dict[int, list] = {}
    for tag, ranking, weight in zip(source_names, rankings, weights):
        if tag == "bm25":
            sorted_ids = [cid for cid, _ in sorted(ranking.items(), key=lambda kv: kv[1])]
        else:
            sorted_ids = [cid for cid, _ in sorted(ranking.items(), key=lambda kv: -kv[1])]
        for rank, cid in enumerate(sorted_ids, start=1):
            aggregate[cid] = aggregate.get(cid, 0.0) + weight * (1.0 / (k + rank))
            sources.setdefault(cid, []).append(tag)
    fused = sorted(
        ((cid, score, sources[cid]) for cid, score in aggregate.items()),
        key=lambda t: -t[1],
    )
    return fused
